### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CHbloom** [rr-learning/trifinger_rl_datasets#1]
I would like to take the liberty of asking when your dataset will be released. I would like to conduct research based on this. Thank you for your help

**Comment by nicoguertler** [comment]
Hi, the datasets are released now, sorry for the late response. Note that the weak-n-expert and half-expert datasets as well as the trifinger-cube-lift-sim-expert-* datasets contained some errors before May 15, 2023. So if you downloaded before that date, please delete the local files and download again.
